name: Package toolbox and publish release

env:
  MATLAB_VER: ${{ vars.MATLAB_VER }}

# Run workflow when a tag is created
on:
  push:
    tags: 
      - 'v*'
      
jobs:
  main-workflow:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    
  packageToolbox:
    needs: main-workflow
    
    # The type of runner that the job will run on
    runs-on: matlab
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.REPO_READ_TOKEN }}
          
      # Download firmware mldatx file from bossdevice-firmware
      - name: Download firmware artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.REPO_READ_TOKEN }}
          workflow: main.yml
          repo: sync2brain/bossdevice-firmware
          branch: main
          search_artifacts: true
          name: bossdevice-firmware-*
          name_is_regexp: true
          skip_unpack: true
          if_no_artifact_found: fail

      - name: Unzip firmware artifacts into firmware folder
        run: |
          Get-ChildItem '.' -Filter bossdevice-firmware-*.zip | Expand-Archive -DestinationPath 'toolbox\dependencies\firmware'
      
      # Download Speedgoat dependendencies
      - name: Download Speedgoat dependencies artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.REPO_READ_TOKEN }}
          workflow: main.yml
          search_artifacts: true
          name: speedgoat-deps-*
          name_is_regexp: true
          skip_unpack: true
          if_no_artifact_found: fail

      - name: Unzip firmware artifacts into firmware folder
        run: |
          Get-ChildItem '.' -Filter speedgoat-deps-*.zip | Expand-Archive -DestinationPath 'toolbox\dependencies\sg' -Force
          
      - name: Cache MATLAB build files
        uses: actions/cache@v3
        with:
          key: matlab-buildtool
          path: |
            .buildtool

      - name: Run MATLAB command
        run: |
          &"$env:ProgramFiles\MATLAB\$env:MATLAB_VER\bin\matlab.exe" -batch "openProject(pwd); buildtool test('noHW') package('${{  github.ref_name }}','${{  github.actor }}');"
      
      # Create new release
      - name: Create a new release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/bossdevice-api-installer.mltbx
          fail_on_unmatched_files: true
          generate_release_notes: true
