name: Package toolbox and publish release

env:
  MATLAB_VER: R2023a

# Run workflow when a tag is created
on:
  push:
    tags: 
      - 'v*'
      
jobs:
  main-workflow:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    
  packageToolbox:
    needs: main-workflow
    
    # The type of runner that the job will run on
    runs-on: matlab
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.REPO_READ_TOKEN }}
          
      # Download firmware mldatx file from bossdevice-firmware. Must create a step for every MATLAB release to add
      - name: Download firmware artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.REPO_READ_TOKEN }}
          workflow: main.yml
          repo: sync2brain/bossdevice-firmware
          branch: main
          search_artifacts: true
          name: bossdevice-firmware-*
          name_is_regexp: true
          path: toolbox/dependencies/firmware
          if_no_artifact_found: fail
          
      - name: Cache MATLAB build files
        uses: actions/cache@v3
        with:
          key: matlab-buildtool
          path: |
            buildUtilities/.buildtool

      - name: Run MATLAB command
        run: |
          &"$env:ProgramFiles\MATLAB\$env:MATLAB_VER\bin\matlab.exe" -batch "openProject(pwd); cd('buildUtilities'); buildtool package('${{  github.ref_name }}','${{  github.actor }}')"
      
      # Create new release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: releases/bossdevice-api-installer.mltbx
          fail_on_unmatched_files: true
          generate_release_notes: true
